---
velociraptor_client_version: "0.77.3"
velociraptor_client_frontend_port: 8000
velociraptor_client_server_inventory_host: "{{ groups['velociraptor_server'][0] }}"
velociraptor_client_windows_temp_dir: C:\Windows\Temp\SENGOAD-Velociraptor
velociraptor_client_windows_msi_path: "{{ velociraptor_client_windows_temp_dir }}\\velociraptor-client-{{ velociraptor_client_version }}.msi"
